In [ ]:
import tensorflow as tf

"A tensor is a generalization of vectors and matrecies to potentially higher dimensions. Interally, Tensorflow represents tensor as n-dimensional arrays of base datatypes"

Each tensor has a type, and a shape.

Shape represents the dimension of data.

## Creating tensors

shapes equal to one are named scalar values.

In [ ]:
string_tensor = tf.Variable("Tensor string", tf.string) #value and datatype
number_tensor=tf.Variable(77, tf.int16)
floating_tensor = tf.Variable (77.7, tf.float64)

## Rank/Degree of Tensors
The number of dimensions in the tensor.

Tensors with one values (scalars) have a rank equal to zero.

When we have an array or a list, we have at least rank one.

In [ ]:
one_rank=tf.Variable (["i"],tf.string)
two_rank=tf.Variable ([["i","i"],["ii","ii"],["iii","iii"]],tf.string)

In [ ]:
tf.rank(two_rank) # the last parameter numpy=? is the rank 

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of tensor
A shape is how many items we have in each dimension


In [ ]:
two_rank.shape 
# 3 elements in the 1st dimension and 2 elements in the 2nd dimension
# we have 3 lists and two elements in each of them 

TensorShape([3, 2])

## Changing the number of shape of tensors
we can represent the same amount of elements in different shapes

In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2= tf.reshape(tensor1, [2,3,1])
tensor3= tf.reshape(tensor2, [3,-1])
# -1 tells the tensor to calculate the size of the dimension in that place 

In [ ]:
print(tensor1) 
# we have one interial list, and two lists inside of that list and 3 elements in each them
print(tensor2)
# reshape data to have 6 elements but in different shape.
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors

*   Variable
*   Constant
*   Placeholder
*   SparseTensor

Variable tensor could change. However the other tensor types are immutable, which means they may not be changed during execution.



## Evaluating Tensors
Evaluating a tensor means to get its value. 

In [ ]:
tf.print(tensor1)

[[[1 1 1]
  [1 1 1]]]


## Example

In [ ]:
t= tf.zeros([2,2,2,2]) 
# => number of elements is equal to the product of the shapes 2*2*2*2=16
print(t)

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [ ]:
tf.reshape(t,[16]) # reshaping

<tf.Tensor: shape=(16,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [ ]:
tf.reshape(t,[8,-1]) #reshaping

<tf.Tensor: shape=(8, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>